import { Business } from './business';

export const BUSINESSES: Business[] = [
    {
        id: 0,
        type: ["spa", "salon"],
        name: "Rainbow Salon",
        address: "232 Sycamore Ave",
        city: "Middletown",
        state: "Pennsylvania",
        zip: "17057",
        phone: "",
        website: "",
        image: "/images/spa1.jpg",
        rating: 3,
        price_level: 3,
        location: 0.56,
        contact_name: "Amanda Anumba",
        contact_email: "amanda.anumba@gmail.com",
        contact_phone: "909-561-9291"
    }, 
    {
        id: 1,
        type: ["spa", "salon"],
        name: "Salon 2",
        address: "3567 High Pointe Commons",
        city: "Harrisburg",
        state: "Pennsylvania",
        zip: "17097",
        phone: "",
        website: "",
        image: "/images/spa2.jpg",
        rating: 3.5,
        price_level: 3.5,
        location: 0.85,
        contact_name: "Amanda Anumba",
        contact_email: "amanda.anumba@gmail.com",
        contact_phone: "909-561-9291"
    }, 
    {
        id: 2,
        type: ["spa", "salon"],
        name: "Salon 3",
        address: "867 Pine St",
        city: "Middletown",
        state: "Pennsylvania",
        zip: "17101",
        phone: "",
        website: "",
        image: "/images/spa3.jpg",
        rating: 4.6,
        price_level: 4.6,
        location: 0.9,
        contact_name: "Amanda Anumba",
        contact_email: "amanda.anumba@gmail.com",
        contact_phone: "909-561-9291"
    },
    {
        id: 3,
        type: ["spa", "salon"],
        name: "Salon 4",
        address: "232 Sycamore Ave",
        city: "Middletown",
        state: "Pennsylvania",
        zip: "17057",
        phone: "",
        website: "",
        image: "/images/spa1.jpg",
        rating: 2.5,
        price_level: 2.5,
        location: 1.2,
        contact_name: "Amanda Anumba",
        contact_email: "amanda.anumba@gmail.com",
        contact_phone: "909-561-9291"
    }
];